In [1]:
import pandas as pd
import requests

In [21]:
APP_ID="aabebcdf"
APP_KEY="84ac0e372e46c2b2a66f9dcb4f6f204e"

In [23]:
APP_ID="aabebcdf"
APP_KEY="84ac0e372e46c2b2a66f9dcb4f6f204e"

roles = [
    "software engineer",
    "data scientist",
    "data analyst",
    "machine learning engineer",
    "backend developer",
    "frontend developer",
    "full stack developer",
    "python developer",
    "java developer",
    "devops engineer",
    "cloud engineer",
    "cyber security",
    "business analyst"
]
max_pages=20
all_dataframes=[]
def fetch_data(roles,page):
    url = f"https://api.adzuna.com/v1/api/jobs/in/search/{page}"
    params={
        "app_id":APP_ID,
        "app_key":APP_KEY,
        "results_per_page":20,
        "what":roles
    }
    response=requests.get(url, params=params)
    if response.status_code != 200:
       print(f"Error: {response.status_code}")
       return pd.DataFrame()
    data=response.json()
    if "results"  not in data:
        return pd.DataFrame()
    return pd.DataFrame(data['results'])
for role in roles:
    print(f'\n Collectioning: {role}')
    for  page in range(1,max_pages+1):
        df=fetch_data(role,page)
        if df.empty:
            print(f"No more jobs for {role}")
            break
        print(f"Page {page}: {len(df)} jobs")
        all_dataframes.append(df)
final_df=pd.concat(all_dataframes,ignore_index=True)
print(final_df.shape)
#final_df.to_csv("raw_jobs.csv", index=False)

 Collectioning: software engineer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: data scientist
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: data analyst
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: machine learning engineer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: backend developer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: frontend developer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: full stack developer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: python developer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: java developer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: devops engineer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: cloud engineer
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: cyber security
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs

 Collectioning: business analyst
Page 1: 20 jobs
Page 2: 20 jobs
Page 3: 20 jobs
Page 4: 20 jobs
Page 5: 20 jobs
Page 6: 20 jobs
Page 7: 20 jobs
Page 8: 20 jobs
Page 9: 20 jobs
Page 10: 20 jobs
Page 11: 20 jobs
Page 12: 20 jobs
Page 13: 20 jobs
Page 14: 20 jobs
Page 15: 20 jobs
Page 16: 20 jobs
Page 17: 20 jobs
Page 18: 20 jobs
Page 19: 20 jobs
Page 20: 20 jobs
(5200, 17)

In [24]:
final_df['company']=final_df['company'].apply(lambda x:x.get('display_name') if isinstance(x,dict) else None )
final_df['category']=final_df['category'].apply(lambda x:x.get('label') if isinstance(x,dict) else None)
final_df['location']=final_df['location'].apply(lambda x:x.get('display_name') if isinstance(x,dict) else None)

In [25]:
final_df.head()

,created,latitude,title,adref,location,longitude,salary_is_predicted,description,company,redirect_url,__CLASS__,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTc4NTc3MjA3MiIsI...,"Bangalore, Karnataka",77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Adzuna::API::Response::Job,Engineering Jobs,5785772072,full_time,NaN,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Bangalore, Karnataka",77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,Adzuna::API::Response::Job,IT Jobs,5794768004,full_time,NaN,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Hyderabad, Telangana",78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,Adzuna::API::Response::Job,IT Jobs,5785773087,full_time,NaN,NaN,NaN
3,2026-07-07T05:28:33Z,12.95703,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Bangalore, Karnataka",77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5790410357?se=bi...,Adzuna::API::Response::Job,IT Jobs,5790410357,full_time,NaN,NaN,NaN
4,2026-07-09T17:58:24Z,19.00821,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Mumbai, Maharashtra",72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,Adzuna::API::Response::Job,IT Jobs,5794153227,full_time,NaN,NaN,NaN

In [26]:
final_df.shape

(5200, 17)

In [28]:
final_df.columns

Index(['created', 'latitude', 'title', 'adref', 'location', 'longitude',
       'salary_is_predicted', 'description', 'company', 'redirect_url',
       '__CLASS__', 'category', 'id', 'contract_time', 'contract_type',
       'salary_min', 'salary_max'],
      dtype='object')

In [27]:
final_df.to_csv("raw_jobs_adzuna.csv", index=False)

In [27]:
respone=requests.get("https://api.adzuna.com/v1/api/jobs/in/search/2?app_id=aabebcdf&app_key=84ac0e372e46c2b2a66f9dcb4f6f204e&results_per_page=20")

In [28]:
data=respone.json()

In [30]:
print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['mean', 'results', 'count', '__CLASS__'])

In [30]:
#Now get data from greenhouse api 
working_boards=[]
boards = ["stripe","canva","notion","figma","mongodb","hashicorp","datadog","circleci","cockroachlabs","snyk",
    "plaid","asana","gusto","checkr","flexport", "ramp","brex", "rippling","vercel","zapier"]
working_board=[]
for board in boards:
    url = f"https://boards-api.greenhouse.io/v1/boards/{work_board}/jobs?content=true"
    response=requests.get(url)
    if response.status_code ==200:
        print(f'{board}')
        working_boards.append(board)
    else:
          print(f"NotWorking {board} ({response.status_code})")
print("\nWorking boards:")
print(working_boards)

stripe
canva
notion
figma
mongodb
hashicorp
datadog
circleci
cockroachlabs
snyk
plaid
asana
gusto
checkr
flexport
ramp
brex
rippling
vercel
zapier

Working boards:
['stripe', 'canva', 'notion', 'figma', 'mongodb', 'hashicorp', 'datadog', 'circleci', 'cockroachlabs', 'snyk', 'plaid', 'asana', 'gusto', 'checkr', 'flexport', 'ramp', 'brex', 'rippling', 'vercel', 'zapier']

In [31]:
all_dataframes_2 = []
for work_board in working_boards:
    print(f"Collecting {work_board}...")
    url= f"https://boards-api.greenhouse.io/v1/boards/{work_board}/jobs?content=true"
    response = requests.get(url)
    if response.status_code != 200:
         continue
    data=response.json()
    df=pd.DataFrame(data['jobs'])
    df["company_board"] = board

    all_dataframes_2.append(df)

greenhouse_df = pd.concat(all_dataframes_2, ignore_index=True)

print(greenhouse_df.shape)

Collecting stripe...
Collecting canva...
Collecting notion...
Collecting figma...
Collecting mongodb...
Collecting hashicorp...
Collecting datadog...
Collecting circleci...
Collecting cockroachlabs...
Collecting snyk...
Collecting plaid...
Collecting asana...
Collecting gusto...
Collecting checkr...
Collecting flexport...
Collecting ramp...
Collecting brex...
Collecting rippling...
Collecting vercel...
Collecting zapier...
(2305, 21)

In [32]:
greenhouse_df.head()

,absolute_url,data_compliance,internal_job_id,location,metadata,id,updated_at,requisition_id,title,company_name,...,language,application_deadline,content,departments,offices,ai_disclaimer,include_ai_disclaimer,ai_opt_out_request_url,education,company_board
0,https://stripe.com/jobs/search?gh_jid=7954688,"[{'type': 'gdpr', 'requires_consent': False, '...",3453698.0,"{'name': 'San Francisco, CA'}",None,7954688,2026-07-13T14:37:36-04:00,See Opening ID,"Account Executive, AI Sales (Grower)",Stripe,...,en,None,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,"[{'id': 380786, 'name': '1654 Account Executiv...","[{'id': 65234, 'name': 'US', 'location': None,...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
1,https://stripe.com/jobs/search?gh_jid=8042978,"[{'type': 'gdpr', 'requires_consent': False, '...",3486109.0,{'name': 'Japan'},None,8042978,2026-07-02T21:13:43-04:00,See Opening ID,"Account Executive, Commercial Grower (Japanese...",Stripe,...,ja,None,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 87012, 'name': 'Japan Locations', 'loc...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
2,https://stripe.com/jobs/search?gh_jid=7789539,"[{'type': 'gdpr', 'requires_consent': False, '...",3407094.0,{'name': 'Japan'},None,7789539,2026-07-02T21:14:52-04:00,See Opening ID,"Account Executive, Commercial Hunter (Japanese...",Stripe,...,ja,None,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 87012, 'name': 'Japan Locations', 'loc...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
3,https://stripe.com/jobs/search?gh_jid=7893199,"[{'type': 'gdpr', 'requires_consent': False, '...",3431456.0,{'name': 'Singapore'},None,7893199,2026-06-26T17:05:39-04:00,See Opening ID,"Account Executive, Cross Border China",Stripe,...,en,None,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 86997, 'name': 'Singapore Locations', ...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
4,https://stripe.com/jobs/search?gh_jid=7993151,"[{'type': 'gdpr', 'requires_consent': False, '...",3467410.0,"{'name': 'US-Remote, US-San Francisco, US-Chic...",None,7993151,2026-07-01T10:19:50-04:00,See Opening ID,"Account Executive - Enterprise, Grower",Stripe,...,en,None,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81430, 'name': '1175 Enterprise - Acco...","[{'id': 65234, 'name': 'US', 'location': None,...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier

In [12]:
#greenhouse_df['location']=greenhouse_df['location'].apply(lambda x:x.get('name') if isinstance(x,dict) else None)

In [33]:
greenhouse_df.head()

,absolute_url,data_compliance,internal_job_id,location,metadata,id,updated_at,requisition_id,title,company_name,...,language,application_deadline,content,departments,offices,ai_disclaimer,include_ai_disclaimer,ai_opt_out_request_url,education,company_board
0,https://stripe.com/jobs/search?gh_jid=7954688,"[{'type': 'gdpr', 'requires_consent': False, '...",3453698.0,"{'name': 'San Francisco, CA'}",None,7954688,2026-07-13T14:37:36-04:00,See Opening ID,"Account Executive, AI Sales (Grower)",Stripe,...,en,None,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,"[{'id': 380786, 'name': '1654 Account Executiv...","[{'id': 65234, 'name': 'US', 'location': None,...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
1,https://stripe.com/jobs/search?gh_jid=8042978,"[{'type': 'gdpr', 'requires_consent': False, '...",3486109.0,{'name': 'Japan'},None,8042978,2026-07-02T21:13:43-04:00,See Opening ID,"Account Executive, Commercial Grower (Japanese...",Stripe,...,ja,None,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 87012, 'name': 'Japan Locations', 'loc...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
2,https://stripe.com/jobs/search?gh_jid=7789539,"[{'type': 'gdpr', 'requires_consent': False, '...",3407094.0,{'name': 'Japan'},None,7789539,2026-07-02T21:14:52-04:00,See Opening ID,"Account Executive, Commercial Hunter (Japanese...",Stripe,...,ja,None,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 87012, 'name': 'Japan Locations', 'loc...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
3,https://stripe.com/jobs/search?gh_jid=7893199,"[{'type': 'gdpr', 'requires_consent': False, '...",3431456.0,{'name': 'Singapore'},None,7893199,2026-06-26T17:05:39-04:00,See Opening ID,"Account Executive, Cross Border China",Stripe,...,en,None,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 86997, 'name': 'Singapore Locations', ...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
4,https://stripe.com/jobs/search?gh_jid=7993151,"[{'type': 'gdpr', 'requires_consent': False, '...",3467410.0,"{'name': 'US-Remote, US-San Francisco, US-Chic...",None,7993151,2026-07-01T10:19:50-04:00,See Opening ID,"Account Executive - Enterprise, Grower",Stripe,...,en,None,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81430, 'name': '1175 Enterprise - Acco...","[{'id': 65234, 'name': 'US', 'location': None,...",None,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier

In [29]:
greenhouse_df.head(1).T

                                                                      0
absolute_url              https://stripe.com/jobs/search?gh_jid=7954688
data_compliance       [{'type': 'gdpr', 'requires_consent': False, '...
internal_job_id                                               3453698.0
location                                              San Francisco, CA
metadata                                                           None
id                                                              7954688
updated_at                                    2026-07-13T14:37:36-04:00
requisition_id                                           See Opening ID
title                              Account Executive, AI Sales (Grower)
company_name                                                     Stripe
first_published                               2026-06-02T08:58:57-04:00
language                                                             en
application_deadline                                               None
education                                                           NaN
company_board                                                    zapier

In [34]:
greenhouse_df.to_csv("raw_job_greenhouse.csv", index=False)